# Generated by Django 2.2.5 on 2019-11-18 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoProyecto',
            fields=[
                ('cod_estado', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('cod_proyecto', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(max_length=500)),
                ('fecha_inicio_req', models.DateField()),
                ('fecha_fin_req', models.DateField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_modif', models.DateField(auto_now=True)),
                ('estado_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyecto.EstadoProyecto')),
            ],
        ),
    ]
