# Generated by Django 2.2.5 on 2019-11-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='cod_proyecto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
