# Generated by Django 2.2.5 on 2019-11-24 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('proyecto', '0002_auto_20191118_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=50)),
                ('fecha_cierre', models.DateField()),
                ('probabilidad', models.FloatField()),
                ('presentado', models.BooleanField()),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('fecha_modif', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiesgoImpacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=50)),
                ('impacto', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='fecha_creacion',
            new_name='fecha_alta',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='fecha_fin_req',
            new_name='fecha_fin_real',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='fecha_inicio_req',
            new_name='fecha_inicio_real',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='estado_proyecto',
        ),
        migrations.DeleteModel(
            name='EstadoProyecto',
        ),
        migrations.AddField(
            model_name='riesgo',
            name='impacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyecto.RiesgoImpacto'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyecto.Proyecto'),
        ),
    ]
