# Generated by Django 2.2.5 on 2019-11-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('proyecto', '0003_auto_20191124_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riesgo',
            name='fecha_cierre',
            field=models.DateField(blank=True),
        ),
    ]
