# Generated by Django 2.2.5 on 2019-11-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('proyecto', '0004_auto_20191124_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riesgo',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
    ]
