# Generated by Django 2.2.5 on 2019-11-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('proyecto', '0005_auto_20191124_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riesgo',
            name='fecha_cierre',
            field=models.DateField(null=True),
        ),
    ]
