# Generated by Django 2.2.5 on 2019-11-28 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('proyecto', '0007_auto_20191125_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iteracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('fecha_modif', models.DateField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyecto.Proyecto')),
            ],
        ),
    ]
