# Generated by Django 2.2.5 on 2019-11-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('expected_delivery', models.DateTimeField(verbose_name='date published')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
